_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "output_X101/X-101.pth"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1600 # Visual Genome classes usually
    SCORE_THRESH_TEST: 0.05
INPUT:
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
